
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA ENDPRINT ENTERO ID NEWPRINT PARDER PARIZQ PUNTOCOMA SET_PRINT_ESTRELLA SET_PRINT_O SET_PRINT_TRIANGULO SET_PRINT_X T_AMARILLO T_CYAN T_MAGENTA T_NEGROinit            : L_SENTL_SENT : L_SENT SENT\n              | SENT\n    SENT : NEWPRINT ID PUNTOCOMA L_SENT_PRINT ENDPRINT PUNTOCOMA\n    L_SENT_PRINT : L_SENT_PRINT SENT_PRINT\n                    | SENT_PRINT\n    SENT_PRINT : SET_PRINT PARIZQ ENTERO COMA ENTERO COMA COLOR PARDER PUNTOCOMA\n    COLOR : T_CYAN\n             | T_MAGENTA\n             | T_AMARILLO\n             | T_NEGRO\n    SET_PRINT : SET_PRINT_X\n                | SET_PRINT_O\n                | SET_PRINT_TRIANGULO\n                | SET_PRINT_ESTRELLA\n    '
    
_lr_action_items = {'NEWPRINT':([0,2,3,5,18,],[4,4,-3,-2,-4,]),'$end':([1,2,3,5,18,],[0,-1,-3,-2,-4,]),'ID':([4,],[6,]),'PUNTOCOMA':([6,15,28,],[7,18,29,]),'SET_PRINT_X':([7,8,9,16,29,],[11,11,-6,-5,-7,]),'SET_PRINT_O':([7,8,9,16,29,],[12,12,-6,-5,-7,]),'SET_PRINT_TRIANGULO':([7,8,9,16,29,],[13,13,-6,-5,-7,]),'SET_PRINT_ESTRELLA':([7,8,9,16,29,],[14,14,-6,-5,-7,]),'ENDPRINT':([8,9,16,29,],[15,-6,-5,-7,]),'PARIZQ':([10,11,12,13,14,],[17,-12,-13,-14,-15,]),'ENTERO':([17,20,],[19,21,]),'COMA':([19,21,],[20,22,]),'T_CYAN':([22,],[24,]),'T_MAGENTA':([22,],[25,]),'T_AMARILLO':([22,],[26,]),'T_NEGRO':([22,],[27,]),'PARDER':([23,24,25,26,27,],[28,-8,-9,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'L_SENT':([0,],[2,]),'SENT':([0,2,],[3,5,]),'L_SENT_PRINT':([7,],[8,]),'SENT_PRINT':([7,8,],[9,16,]),'SET_PRINT':([7,8,],[10,10,]),'COLOR':([22,],[23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> L_SENT','init',1,'p_init','Gramatica.py',86),
  ('L_SENT -> L_SENT SENT','L_SENT',2,'p_LSENT','Gramatica.py',90),
  ('L_SENT -> SENT','L_SENT',1,'p_LSENT','Gramatica.py',91),
  ('SENT -> NEWPRINT ID PUNTOCOMA L_SENT_PRINT ENDPRINT PUNTOCOMA','SENT',6,'p_SENT','Gramatica.py',101),
  ('L_SENT_PRINT -> L_SENT_PRINT SENT_PRINT','L_SENT_PRINT',2,'p_L_SENT_PRINT','Gramatica.py',109),
  ('L_SENT_PRINT -> SENT_PRINT','L_SENT_PRINT',1,'p_L_SENT_PRINT','Gramatica.py',110),
  ('SENT_PRINT -> SET_PRINT PARIZQ ENTERO COMA ENTERO COMA COLOR PARDER PUNTOCOMA','SENT_PRINT',9,'p_SENT_PRINT','Gramatica.py',119),
  ('COLOR -> T_CYAN','COLOR',1,'p_COLOR','Gramatica.py',130),
  ('COLOR -> T_MAGENTA','COLOR',1,'p_COLOR','Gramatica.py',131),
  ('COLOR -> T_AMARILLO','COLOR',1,'p_COLOR','Gramatica.py',132),
  ('COLOR -> T_NEGRO','COLOR',1,'p_COLOR','Gramatica.py',133),
  ('SET_PRINT -> SET_PRINT_X','SET_PRINT',1,'p_SET_PRINT','Gramatica.py',143),
  ('SET_PRINT -> SET_PRINT_O','SET_PRINT',1,'p_SET_PRINT','Gramatica.py',144),
  ('SET_PRINT -> SET_PRINT_TRIANGULO','SET_PRINT',1,'p_SET_PRINT','Gramatica.py',145),
  ('SET_PRINT -> SET_PRINT_ESTRELLA','SET_PRINT',1,'p_SET_PRINT','Gramatica.py',146),
]
